rrcar:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Effort Controllers ---------------------------------------
  wheel_left:
    velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: wheel_left_joint
      pid: {p: 0.05, i: 0.0, d: 0.1}
  wheel_right:
    velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: wheel_right_joint
      pid: {p: 0.05, i: 0.0, d: 0.1}
