<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rrcar">

	<xacro:property name="wheel_radius" value="0.05" />
	<xacro:property name="wheel_width" value="0.05" />
	<xacro:property name="wheel_mass" value="0.3" />
	<xacro:property name="body_height" value="0.046" />
	<xacro:property name="body_mass" value="3" />
	<xacro:property name="track_width" value="0.22" />
	<xacro:property name="vehicle_height" value="0.004" />

	<xacro:macro name="wheel_visual">
		<visual>
			<origin xyz="0 0 0" rpy="${M_PI / 2} 0 0" />
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_width}" />
			</geometry>
			<xacro:material_blue />
		</visual>
	</xacro:macro>

	<xacro:macro name="wheel_collision">
		<collision>
			<origin xyz="0 0 0" rpy="${M_PI / 2} 0 0" />
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_width}" />
			</geometry>
		</collision>
	</xacro:macro>

	<xacro:macro name="wheel_transmission" params="name">
		<transmission name="${name}_transmission" type="SimpleTransmission">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="${name}_joint">
				<hardwareInterface>VelocityJointInterface</hardwareInterface>
			</joint>
			<actuator name="${name}_motor">
				<hardwareInterface>VelocityJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
		</transmission>
	</xacro:macro>

	<link name="base_footprint" />

	<joint name="footprint_to_base" type="fixed">
		<parent link="base_footprint" />
		<child link="base_link" />
		<origin xyz="0 0 ${vehicle_height}" rpy="0 0 0" />
	</joint>

	<link name="base_link">
		<visual>
			<origin xyz="0 0 0" rpy="${M_PI / 2} 0 ${M_PI / 2}" />
			<geometry>
				<mesh filename="package://rrcar_description/meshes/base_link.stl" />
			</geometry>
			<xacro:material_orange />
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="${M_PI / 2} 0 ${M_PI / 2}" />
			<geometry>
				<mesh filename="package://rrcar_description/meshes/base_link.stl" />
			</geometry>
			<xacro:material_orange />
		</collision>
		<xacro:default_inertial mass="${body_mass}" origin_xyz="0 0 0" />
	</link>

	<joint name="wheel_left_joint" type="continuous">
		<parent link="base_link" />
		<child link="wheel_left" />
		<origin xyz="0 ${track_width / 2} ${wheel_radius - vehicle_height}" rpy="0 0 0" />
		<axis xyz="0 1 0" />
		<limit effort="8" velocity="30.0" />
		<dynamics damping="0.3" friction="0.2" />
	</joint>
	<xacro:wheel_transmission name="wheel_left" />

	<link name="wheel_left">
		<xacro:wheel_visual />
		<xacro:wheel_collision />
		<xacro:default_inertial mass="${wheel_mass}" origin_xyz="0 0 0" />
	</link>

	<joint name="wheel_right_joint" type="continuous">
		<parent link="base_link" />
		<child link="wheel_right" />
		<origin xyz="0 -${track_width / 2} ${wheel_radius - vehicle_height}" rpy="0 0 0" />
		<axis xyz="0 -1 0" />
		<limit effort="8" velocity="30.0" />
		<dynamics damping="0.3" friction="0.2" />
	</joint>
	<xacro:wheel_transmission name="wheel_right" />

	<link name="wheel_right">
		<xacro:wheel_visual />
		<xacro:wheel_collision />
		<xacro:default_inertial mass="${wheel_mass}" origin_xyz="0 0 0" />
	</link>

	<!-- Sensors -->
	<joint name="camera_joint" type="fixed">
		<axis xyz="0 1 0" />
		<origin xyz="0.14 0 0.04" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="camera_link"/>
	</joint>

	<link name="camera_link">
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.02 0.02 0.01"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.02 0.02 0.01"/>
			</geometry>
			<xacro:material_red />
		</visual>
		<inertial>
			<mass value="1e-4" />
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="1e-5" ixy="0" ixz="0" iyy="1e-5" iyz="0" izz="1e-5" />
		</inertial>
	</link>

	<joint name="hokuyo_joint" type="fixed">
		<axis xyz="0 0 1" />
		<origin xyz="0.13 0 ${body_height}" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="hokuyo_link"/>
	</joint>

	<link name="hokuyo_link">
		<collision>
			<origin xyz="0 0 ${0.029 / 2}" rpy="0 0 0"/>
			<geometry>
				<cylinder radius="0.021" length="0.029"/>
			</geometry>
		</collision>
		<visual>
			<origin xyz="0 0 ${0.029 / 2}" rpy="0 0 0"/>
			<geometry>
				<cylinder radius="0.021" length="0.029"/>
			</geometry>
			<xacro:material_black />
		</visual>
		<inertial>
			<mass value="0.16" />
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia ixx="0.016" ixy="0" ixz="0" iyy="0.016" iyz="0" izz="0.016" />
		</inertial>
	</link>

  <xacro:include filename="$(find rrcar_description)/urdf/rrcar.gazebo" />

</robot>
